export enum PermissionsEnum {
  SUPER_ADMIN_EDIT = 'SUPER_ADMIN_EDIT',
  ALL_RESTAURANTS_VIEW = 'ALL_RESTAURANTS_VIEW',
  ALL_USERS_EDIT = 'ALL_USERS_EDIT',
  ALL_USERS_VIEW = 'ALL_USERS_VIEW',
  ALL_RESTAURANTS_EDIT = 'ALL_RESTAURANTS_EDIT',
  CHANGE_ROLES_PERMISSIONS = 'CHANGE_ROLES_PERMISSIONS',
  RESTAURANTS_VIEW = 'RESTAURANTS_VIEW',
  RESTAURANTS_EDIT = 'RESTAURANTS_EDIT',
  TABLES_VIEW = 'TABLES_VIEW',
  TABLES_EDIT = 'TABLES_EDIT',
  ITEMS_VIEW = 'ITEMS_VIEW',
  ITEMS_EDIT = 'ITEMS_EDIT',
}

export const PermissionGroups = {
  GENERAL: [
    PermissionsEnum.RESTAURANTS_VIEW,
    PermissionsEnum.RESTAURANTS_EDIT,
    PermissionsEnum.TABLES_VIEW,
    PermissionsEnum.TABLES_EDIT,
    PermissionsEnum.ITEMS_VIEW,
    PermissionsEnum.ITEMS_EDIT,
    PermissionsEnum.CHANGE_ROLES_PERMISSIONS,
  ],
  ADMINSTRATION: [
    PermissionsEnum.SUPER_ADMIN_EDIT,
    PermissionsEnum.ALL_RESTAURANTS_VIEW,
    PermissionsEnum.ALL_RESTAURANTS_EDIT,
    PermissionsEnum.ALL_USERS_VIEW,
    PermissionsEnum.ALL_USERS_EDIT,
  ],
};
