export enum ProfileTransitionEnum {
  CONFIGURE_PAYMENT = 'CONFIGURE_PAYMENT',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  CREATE_PASSWORD = 'CREATE_PASSWORD',
  ACTIVATE = 'ACTIVATE',
  SUSPEND = 'SUSPEND',
  ARCHIVE = 'ARCHIVE',
}
